#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

USAGE="$(cat << EOF
"$(basename "$0")" -- Sync org files to and from a mounted webdav remote.

where:
    help    shows this help text
    pull    copies remote files locally
    push    copies local files to the remote
EOF
)"

# Bail out if rsync doesn't exist.
if ! command -v rsync &> /dev/null; then
  echo "rsync could not be found"
  exit 1
fi

# Bail out if the webdav volume isn't mounted.
if [ ! -d /Volumes/webdav.fastmail.com/iam.chrisdeluca.me/files/org ]; then
  echo "Webdav volume not mounted"
  exit 2
fi

if [ $# -eq 0 ]; then
  echo "$USAGE"
  exit 0
fi

if [ "$1" == "push" ]; then
  # Push the local org collection to the webdav volume.
  rsync -a ~/org/ /Volumes/webdav.fastmail.com/iam.chrisdeluca.me/files/org/
elif [ "$1" == "pull" ]; then
  # Pull the remote webdav org org collection to the local disk.
  rsync -a /Volumes/webdav.fastmail.com/iam.chrisdeluca.me/files/org/ ~/org/
else
  echo "$USAGE"
  exit 0
fi
